// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: web3db.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinNetworkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerId []byte `protobuf:"bytes,1,opt,name=peerId,proto3" json:"peerId,omitempty"`
}

func (x *JoinNetworkRequest) Reset() {
	*x = JoinNetworkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web3db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinNetworkRequest) ProtoMessage() {}

func (x *JoinNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web3db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinNetworkRequest.ProtoReflect.Descriptor instead.
func (*JoinNetworkRequest) Descriptor() ([]byte, []int) {
	return file_web3db_proto_rawDescGZIP(), []int{0}
}

func (x *JoinNetworkRequest) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

type JoinNetworkReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *InternalMetadataThreadInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *JoinNetworkReply) Reset() {
	*x = JoinNetworkReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web3db_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinNetworkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinNetworkReply) ProtoMessage() {}

func (x *JoinNetworkReply) ProtoReflect() protoreflect.Message {
	mi := &file_web3db_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinNetworkReply.ProtoReflect.Descriptor instead.
func (*JoinNetworkReply) Descriptor() ([]byte, []int) {
	return file_web3db_proto_rawDescGZIP(), []int{1}
}

func (x *JoinNetworkReply) GetInfo() *InternalMetadataThreadInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type InternalMetadataThreadInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addrs [][]byte `protobuf:"bytes,1,rep,name=addrs,proto3" json:"addrs,omitempty"`
	Key   []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Name  string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *InternalMetadataThreadInfo) Reset() {
	*x = InternalMetadataThreadInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web3db_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternalMetadataThreadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalMetadataThreadInfo) ProtoMessage() {}

func (x *InternalMetadataThreadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_web3db_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalMetadataThreadInfo.ProtoReflect.Descriptor instead.
func (*InternalMetadataThreadInfo) Descriptor() ([]byte, []int) {
	return file_web3db_proto_rawDescGZIP(), []int{2}
}

func (x *InternalMetadataThreadInfo) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *InternalMetadataThreadInfo) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *InternalMetadataThreadInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AssignMasterNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AssignMasterNodeRequest) Reset() {
	*x = AssignMasterNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web3db_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignMasterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignMasterNodeRequest) ProtoMessage() {}

func (x *AssignMasterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web3db_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignMasterNodeRequest.ProtoReflect.Descriptor instead.
func (*AssignMasterNodeRequest) Descriptor() ([]byte, []int) {
	return file_web3db_proto_rawDescGZIP(), []int{3}
}

type AssignMasterNodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AssignMasterNodeReply) Reset() {
	*x = AssignMasterNodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web3db_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignMasterNodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignMasterNodeReply) ProtoMessage() {}

func (x *AssignMasterNodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_web3db_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignMasterNodeReply.ProtoReflect.Descriptor instead.
func (*AssignMasterNodeReply) Descriptor() ([]byte, []int) {
	return file_web3db_proto_rawDescGZIP(), []int{4}
}

var File_web3db_proto protoreflect.FileDescriptor

var file_web3db_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x77, 0x65, 0x62, 0x33, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x77, 0x65, 0x62, 0x33, 0x64, 0x62, 0x2e, 0x70, 0x62, 0x22, 0x2c, 0x0a, 0x12, 0x4a, 0x6f, 0x69,
	0x6e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x39, 0x0a, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x77, 0x65, 0x62, 0x33,
	0x64, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x58, 0x0a, 0x1a, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x19, 0x0a, 0x17, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x32, 0x61, 0x0a, 0x12, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x73, 0x12, 0x4b, 0x0a, 0x0b, 0x4a, 0x6f,
	0x69, 0x6e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x1d, 0x2e, 0x77, 0x65, 0x62, 0x33,
	0x64, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x77, 0x65, 0x62, 0x33, 0x64,
	0x62, 0x2e, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x32, 0x6d, 0x0a, 0x0f, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x73, 0x12, 0x5a, 0x0a, 0x10, 0x41, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x22,
	0x2e, 0x77, 0x65, 0x62, 0x33, 0x64, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67,
	0x6e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x77, 0x65, 0x62, 0x33, 0x64, 0x62, 0x2e, 0x70, 0x62, 0x2e, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_web3db_proto_rawDescOnce sync.Once
	file_web3db_proto_rawDescData = file_web3db_proto_rawDesc
)

func file_web3db_proto_rawDescGZIP() []byte {
	file_web3db_proto_rawDescOnce.Do(func() {
		file_web3db_proto_rawDescData = protoimpl.X.CompressGZIP(file_web3db_proto_rawDescData)
	})
	return file_web3db_proto_rawDescData
}

var file_web3db_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_web3db_proto_goTypes = []interface{}{
	(*JoinNetworkRequest)(nil),         // 0: web3db.pb.JoinNetworkRequest
	(*JoinNetworkReply)(nil),           // 1: web3db.pb.JoinNetworkReply
	(*InternalMetadataThreadInfo)(nil), // 2: web3db.pb.InternalMetadataThreadInfo
	(*AssignMasterNodeRequest)(nil),    // 3: web3db.pb.AssignMasterNodeRequest
	(*AssignMasterNodeReply)(nil),      // 4: web3db.pb.AssignMasterNodeReply
}
var file_web3db_proto_depIdxs = []int32{
	2, // 0: web3db.pb.JoinNetworkReply.info:type_name -> web3db.pb.InternalMetadataThreadInfo
	0, // 1: web3db.pb.BootstrappingComms.JoinNetwork:input_type -> web3db.pb.JoinNetworkRequest
	3, // 2: web3db.pb.MasterNodeComms.AssignMasterNode:input_type -> web3db.pb.AssignMasterNodeRequest
	1, // 3: web3db.pb.BootstrappingComms.JoinNetwork:output_type -> web3db.pb.JoinNetworkReply
	4, // 4: web3db.pb.MasterNodeComms.AssignMasterNode:output_type -> web3db.pb.AssignMasterNodeReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_web3db_proto_init() }
func file_web3db_proto_init() {
	if File_web3db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_web3db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinNetworkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web3db_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinNetworkReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web3db_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InternalMetadataThreadInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web3db_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignMasterNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web3db_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignMasterNodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_web3db_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_web3db_proto_goTypes,
		DependencyIndexes: file_web3db_proto_depIdxs,
		MessageInfos:      file_web3db_proto_msgTypes,
	}.Build()
	File_web3db_proto = out.File
	file_web3db_proto_rawDesc = nil
	file_web3db_proto_goTypes = nil
	file_web3db_proto_depIdxs = nil
}
